# Generated by Django 5.2.7 on 2025-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_historicalpaymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactionitem',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='Whether this item has been refunded'),
        ),
        migrations.AddField(
            model_name='historicaltransactionitem',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When this item was refunded', null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='Whether this item has been refunded'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When this item was refunded', null=True),
        ),
    ]
